# Generated by Django 3.2.6 on 2021-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='current_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maze',
            name='current_y',
            field=models.IntegerField(default=0),
        ),
    ]
