# Generated by Django 3.2.6 on 2021-09-01 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maze', '0002_auto_20210901_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField(choices=[(10, 'North'), (20, 'East'), (30, 'South'), (40, 'West')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('maze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maze.maze')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
