# Generated by Django 3.2.6 on 2021-09-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0003_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='maze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='maze.maze'),
        ),
        migrations.AlterField(
            model_name='step',
            name='direction',
            field=models.IntegerField(choices=[(10, 'North'), (20, 'East'), (30, 'South'), (40, 'West')], default=None),
        ),
    ]
