# Generated by Django 3.2.6 on 2021-09-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0004_auto_20210902_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='author',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='step',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='reader',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
