# Generated by Django 3.2.7 on 2021-09-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0006_maze_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='end_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maze',
            name='end_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maze',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maze',
            name='height',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='maze',
            name='width',
            field=models.IntegerField(default=10),
        ),
    ]
