# Generated by Django 3.2.7 on 2022-03-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0008_maze_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(10, 'Easy'), (20, 'Medium'), (30, 'Hard')], default=10)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='maze',
            name='task_difficulty',
            field=models.IntegerField(blank=True, choices=[(10, 'Easy'), (20, 'Medium'), (30, 'Hard')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='maze',
            name='next_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maze.task'),
        ),
        migrations.AddField(
            model_name='step',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maze.task'),
        ),
    ]
