# Generated by Django 3.2.7 on 2022-06-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0009_auto_20220305_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='last_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
