# Generated by Django 3.2.7 on 2022-06-08 10:45
from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def set_last_updated(apps, schema_editor):
    Maze = apps.get_model("maze", "Maze")
    now = timezone.now()

    for maze in Maze.objects.all():
        latest_step = maze.step_set.all().order_by("timestamp").last()
        if latest_step:
            maze.last_updated = latest_step.timestamp
            maze.save()
            continue
        maze.last_updated = now - timedelta(days=365)
        maze.save()


class Migration(migrations.Migration):

    dependencies = [
        ("maze", "0010_maze_last_updated"),
    ]

    operations = [
        migrations.RunPython(set_last_updated, migrations.RunPython.noop),
    ]
