# Generated by Django 4.2.11 on 2024-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maze", "0013_category_maze_category_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
