# Generated by Django 4.2.11 on 2024-03-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maze", "0014_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="maze.category",
            ),
        ),
    ]
